spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/mintiz
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialize : true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

logging.level:
  org.hibernate.SQL: debug
  #org.hibernate.type: trace

file:
  dir: C:/dev/
  #dir: C:/Users/ADMIN/Documents/img/
  #dir: /Users/jimin/dev/img
